---
title: "Supplemental table S5 + Figure 2"
output: html_notebook
---

# Library

```{r}
library(tidyverse)
```


# Notes

This file contains the code for overall measures as reported in the text of the manuscript, as well as the code used for generation of plots and tables. 

# Load and modify WHO data

```{r}
cvd_who_mortality <-  readxl::read_excel(file.path(path_data, "cvd-who-070225.xlsx"))

who<-cvd_who_mortality %>% 
  filter(country=="Norway") %>% 
  filter(year %in% c("2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016")) %>% 
  mutate(agegroup = str_replace(agegroup, "\\[", ""),
         agegroup = str_replace(agegroup,  "\\]", ""),
         crude_rate_per_100000 = as.numeric(death_rate_100000)) %>% 
  group_by(agegroup, sex) %>% 
  summarise(avg_crude_rate = mean(crude_rate_per_100000, na.rm=T))
```

## Age-adjusted SMR

### Overall

```{r}
# Step 1: Make new dataset with age categories corresponding to WHO data

data_std<-df %>%
   mutate(cvd = case_when(str_detect(diagnose_underliggende, "^I") ~ "CVD",
                          TRUE~"None"),
     agegroup = as.factor(case_when(alder_aar < 1                     ~ "0",
    alder_aar >= 1 & alder_aar <= 4   ~ "1-4",
    alder_aar >= 5 & alder_aar <= 9   ~ "5-9",
    alder_aar >= 10 & alder_aar <= 14 ~ "10-14",
    alder_aar >= 15 & alder_aar <= 19 ~ "15-19",
    alder_aar >= 20 & alder_aar <= 24 ~ "20-24",
    alder_aar >= 25 & alder_aar <= 29 ~ "25-29",
    alder_aar >= 30 & alder_aar <= 34 ~ "30-34",
    alder_aar >= 35 & alder_aar <= 39 ~ "35-39",
    alder_aar >= 40 & alder_aar <= 44 ~ "40-44",
    alder_aar >= 45 & alder_aar <= 49 ~ "45-49",
    alder_aar >= 50 & alder_aar <= 54 ~ "50-54",
    alder_aar >= 55 & alder_aar <= 59 ~ "55-59",
    alder_aar >= 60 & alder_aar <= 64 ~ "60-64",
    alder_aar >= 65 & alder_aar <= 69 ~ "65-69",
    alder_aar >= 70 & alder_aar <= 74 ~ "70-74",
    alder_aar >= 75 & alder_aar <= 79 ~ "75-79",
    alder_aar >= 80 & alder_aar <= 84 ~ "80-84",
    alder_aar >= 85                 ~ "85+",
  )))


data_std_tot <- data_std %>% 
   group_by(agegroup) %>% 
   summarise(n = n()) %>%
  mutate(n = as.numeric(n)) %>% 
  add_row(agegroup="All", n=sum(.$n)) %>% 
  left_join(who, by="agegroup") %>% 
  filter(sex == "All") %>% 
  mutate(avg_rate_prop = avg_crude_rate/100000) %>% 
  mutate(expected_cases = round(avg_rate_prop*n,2)) %>% 
  ungroup()

# N observed cases is 2865

# Compute age-standardized SMR +/- CI

data_std_tot %>% 
  summarise(total_expected = sum(expected_cases[1:19], na.rm=T)) %>% 
  mutate(SMR = 2865/total_expected,
         ci.lower = SMR-(1.96*(sqrt(2865)/total_expected)),
         ci.upper = SMR+(1.96*(sqrt(2865)/total_expected)))

# Quality control by Poisson regression

obs = 2865
exp = 55.59

fit = glm(obs~offset(log(exp)), family=poisson)
summary(fit)
exp(coef(fit))
exp(confint(fit))
```

### By sex

```{r}
# Step 1: Modify dataset

data_std_bysex<-data_std%>%
  group_by(agegroup, kjonn_k, cvd) %>% 
 summarise(count = n(), .groups = 'drop') %>%
  mutate(n = count) %>% 
  # Pivot the data to have separate columns for 'None' and 'CVD'
  tidyr::pivot_wider(
    names_from = cvd,
    values_from = count,
    names_prefix = "n_cvd_",
    values_fill = list(count = 0)
  ) %>%
  # Optionally rename the columns for clarity
  rename(n_noCVD = n_cvd_None, observed= n_cvd_CVD) %>% 
   rename(sex = kjonn_k) %>% 
  mutate(sex = as.factor(sex),
         sex = fct_recode(sex, "Female" = "2", 
                          "Male" = "1"))

# Step 2: Modify and merge with WHO data 
obs_exp_bysex<-data_std_bysex %>%             
  group_by(agegroup) %>% 
  summarise(n = sum(n), ,
            sex = "All", 
            n_noCVD=sum(n_noCVD),
            observed =sum(observed),
            .groups = 'drop') %>% 
  bind_rows(data_std_bysex) %>% 
  arrange(agegroup, sex) %>% 
  mutate(n = as.numeric(n)) %>% 
  left_join(who, by=c("agegroup", "sex")) %>% 
  mutate(avg_rate_prop = avg_crude_rate/100000) %>% 
  mutate(expected_cases = round(avg_rate_prop*n,2)) %>% 
  ungroup() %>% 
  filter(sex != "All") %>% 
  group_by(sex) %>% 
  summarise(observed = sum(observed), 
            expected=sum(expected_cases))



# Step 3: Make the model  
model<-obs_exp_bysex %>% 
  glm(observed~as.factor(sex)+offset(log(expected)), family="poisson", data=.) 

# Step 4: Check the model
summary(model)


# Step 5: Extract estimates and confidence intervals
library(emmeans)

emm <- emmeans(model, "sex", type="response", offset=log(1))
emm %>% as.tibble()
```

### Temporal trends

```{r}
#Step 1: Modify dataset to take years into account

data_std_byyear<-data_std %>%
  group_by(agegroup, kjonn_k, cvd, daar) %>% 
 summarise(count = n(), .groups = 'drop') %>%
  mutate(n = count) %>% 
  # Pivot the data to have separate columns for 'None' and 'CVD'
  tidyr::pivot_wider(
    names_from = cvd,
    values_from = count,
    names_prefix = "n_cvd_",
    values_fill = list(count = 0)
  ) %>%
  # Optionally rename the columns for clarity
  rename(n_noCVD = n_cvd_None, observed= n_cvd_CVD) %>% 
   rename(sex = kjonn_k) %>% 
  mutate(sex = as.factor(sex),
         sex = fct_recode(sex, "Female" = "2", 
                          "Male" = "1"))

# Step 2: Modify and merge with WHO data 

obs_exp_bysex<-data_std_byyear %>%  
   group_by(agegroup, daar) %>% 
  summarise(n = sum(n), ,
            sex = "All", 
            n_noCVD=sum(n_noCVD),
            observed =sum(observed),
            .groups = 'drop') %>% 
  bind_rows(data_std_byyear) %>%  
  mutate(n = as.numeric(n)) %>% 
  left_join(who, by=c("agegroup", "sex")) %>% 
  mutate(avg_rate_prop = avg_crude_rate/100000) %>% 
  mutate(expected_cases = round(avg_rate_prop*n,2)) %>% 
  ungroup() %>% 
  group_by(daar, sex) %>% 
  summarise(observed = sum(observed), 
            expected=sum(expected_cases))

# Step 3: Make model taking year of death into account
  
model<-obs_exp_bysex %>% 
  glm(observed~as.factor(daar)+as.factor(sex)+offset(log(expected)), family="poisson", data=.)

# Step 4: Check estimates

summary(model)

# Step 5: Extract yearly rates and confidence intervals and wirte toe xcel
library(emmeans)

emm <- emmeans(model, specs=c("daar", "sex"), type="response", offset=log(1))

yearly_rates <- as.tibble(emm) %>% 
  select(Sex = sex, Year = daar, SMR = rate, lcl=asymp.LCL, ucl = asymp.UCL) %>% 
  mutate(across(SMR:ucl, ~round(., 1)),
         SMR = paste0(SMR, " (", lcl, ", ", ucl, ")")) %>%
  select(-lcl:-ucl) %>% 
  pivot_wider(names_from = "Sex", values_from=SMR)

writexl::write_xlsx(yearly_rates, file.path(path_res, "tables/supplemental-table-s5-yearly-rates.xlsx"))

# Step 6: Make plot
emm %>% as_tibble() %>% 
  ggplot(aes(x=daar, y=rate, group=sex, color=sex, lty=sex)) +
  geom_line(size =1) +
  geom_point(aes(fill=sex), shape=21, color="black", size=2) +
  theme_classic() +
  xlab(label="Year") +
  ylab(label="aSMR") +
  theme(legend.title=element_blank(),
        axis.text = element_text(size=12, color="black"),
        axis.title=element_text(size=12, color="black"),
        legend.text=element_text(size=12, color="black")) +
  viridis::scale_fill_viridis(discrete=T, option="D", begin=0.4, end=0.8) +
  viridis::scale_color_viridis(discrete=T, option="D", begin=0.4, end=0.8) +
  scale_x_continuous(breaks=seq(2004,2021,1)) +
  theme(axis.text.x = element_text(angle=45, margin = margin(t = 10, r = 0, b = 0, l = 0)))


# Step 7: make plot  
ggsave(file.path(path_res, ("figures/fig-2-temporal-trends-020425.png")), dpi=300, width=6, height=6)
  

```





