---
title: "Supplemental table S6 + Figure 3"
author: "Thomas Olsen"
output: github_document
---

# Library

```{r}
library(tidyverse)
```


# Load and modify WHO data

```{r}
cvd_who_mortality <-  readxl::read_excel(file.path(path_data, "cvd-who-070225.xlsx"))

who<-cvd_who_mortality %>% 
  filter(country=="Norway") %>% 
  filter(year %in% c("2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016")) %>% 
  mutate(agegroup = str_replace(agegroup, "\\[", ""),
         agegroup = str_replace(agegroup,  "\\]", ""),
         crude_rate_per_100000 = as.numeric(death_rate_100000)) %>% 
  group_by(agegroup, sex) %>% 
  summarise(avg_crude_rate = mean(crude_rate_per_100000, na.rm=T))
```

## Prepare dataset

```{r}
# Prepare dataset

data_age<-df %>%
   mutate(cvd = case_when(str_detect(diagnose_underliggende, "^I") ~ 1,
                          TRUE~0),
     agegroup = as.factor(case_when(alder_aar < 1                     ~ "0",
    alder_aar >= 1 & alder_aar <= 4   ~ "1-4",
    alder_aar >= 5 & alder_aar <= 9   ~ "5-9",
    alder_aar >= 10 & alder_aar <= 14 ~ "10-14",
    alder_aar >= 15 & alder_aar <= 19 ~ "15-19",
    alder_aar >= 20 & alder_aar <= 24 ~ "20-24",
    alder_aar >= 25 & alder_aar <= 29 ~ "25-29",
    alder_aar >= 30 & alder_aar <= 34 ~ "30-34",
    alder_aar >= 35 & alder_aar <= 39 ~ "35-39",
    alder_aar >= 40 & alder_aar <= 44 ~ "40-44",
    alder_aar >= 45 & alder_aar <= 49 ~ "45-49",
    alder_aar >= 50 & alder_aar <= 54 ~ "50-54",
    alder_aar >= 55 & alder_aar <= 59 ~ "55-59",
    alder_aar >= 60 & alder_aar <= 64 ~ "60-64",
    alder_aar >= 65 & alder_aar <= 69 ~ "65-69",
    alder_aar >= 70 & alder_aar <= 74 ~ "70-74",
    alder_aar >= 75 & alder_aar <= 79 ~ "75-79",
    alder_aar >= 80 & alder_aar <= 84 ~ "80-84",
    alder_aar >= 85                 ~ "85+",
  )),
  polydrug = case_when(antall_påvist_ekskl_alk > 0~1,
                                TRUE~0),
   prev_dia = case_when(prev_dia_1 == 1 | prev_dia_2 == 1 | prev_dia_other == 1~1,
         TRUE~0)) 

# Make tibbles for tables and plotting

process_data <- function(data_age, var_name, var_label, who) {
  data <- data_age %>%
    group_by(agegroup, !!sym(var_name), cvd, kjonn_k) %>%
    summarise(count = n(), .groups = 'drop') %>%
    mutate(n = count) %>%
    pivot_wider(
      names_from = cvd,
      values_from = count,
      names_prefix = "n_cvd_",
      values_fill = list(count = 0)
    ) %>%
    rename(n_noCVD = n_cvd_0, observed = n_cvd_1) %>%
    mutate(!!var_name := fct_recode(as.factor(ifelse(is.na(!!sym(var_name)), 0, !!sym(var_name))), 
                                     "Yes" = "1", "No" = "0")) %>%
    rename(sex = kjonn_k) %>%
    mutate(sex = fct_recode(as.factor(sex), "Female" = "2", "Male" = "1"))

  res <- data %>%
    group_by(agegroup) %>%
    summarise(n = sum(n), n_noCVD = sum(n_noCVD), !!var_name := "All", sex = "All",
              observed = sum(observed), .groups = 'drop') %>%
    bind_rows(data) %>%
    arrange(agegroup, !!sym(var_name), sex) %>%
    mutate(n = as.numeric(n)) %>%
    left_join(who, by = c("agegroup", "sex")) %>%
    mutate(avg_rate_prop = avg_crude_rate / 100000) %>%
    mutate(expected_cases = round(avg_rate_prop * n, 2)) %>%
    ungroup() %>%
    filter(!!sym(var_name) != "All", sex != "All") %>%
    group_by(!!sym(var_name)) %>%
    summarise(observed = sum(observed), expected = sum(expected_cases))

  return(res)
}

# Use your function for each variable
res_prevcvd <- process_data(data_age, "prev_cvd", "CVD", who)
res_dia <- process_data(data_age, "prev_dia", "Diabetes", who)
res_obesity <- process_data(data_age, "prev_obesity", "Obesity", who)
res_lipid <- process_data(data_age, "prev_lipid", "Dyslipidemia", who)
res_prevtsb <- process_data(data_age, "pre_tsb", "Drug Addiction", who)
res_polydrug <- process_data(data_age, "polydrug", "Polydrug Use", who)
res_illegale <- process_data(data_age, "illegale", "Illegal Drug Use",)
res_benzo <- process_data(data_age, "benzo_lastyear", "Benzodiazepines", who)
res_z <- process_data(data_age, "z_lastyear", "Z-drug", who)
res_opioids <- process_data(data_age, "opioids_lastyear", "Opioids", who)

```


### Make table and plot

```{r}

# Step 1: Bind all tibbles

res_strat <- bind_rows(res_prevcvd, res_dia, res_obesity, res_lipid, res_prevtsb, res_polydrug, res_illegale, res_benzo, res_z, res_opioids) %>% 
  pivot_longer(cols=c(prev_cvd, prev_dia, prev_obesity, prev_lipid, pre_tsb, polydrug, illegale, benzo_lastyear, z_lastyear, opioids_lastyear), names_to="condition", values_to="cat") %>% 
  arrange(condition) %>% 
  filter(!is.na(cat)) %>% 
  group_by(condition) %>% 
  nest() %>% 
  mutate(fit = map(data, ~glm(observed~cat+offset(log(expected)), family="poisson", data=.)),
         tidy_fit = map(fit, ~broom::tidy(., conf.int=TRUE, exp=TRUE)),
         emm = map(fit, ~emmeans(., "cat", type="response", offset=log(1))),
         emm = map(emm, ~as_tibble(.)))

# Step 2: Extract p-values

p <- res_strat %>% 
  unnest(tidy_fit) %>% 
  select(Condition = condition, Category=term, p=p.value) %>% 
  mutate(Category = as.factor(Category),
         Category = fct_recode(Category, "No"="(Intercept)",
                               "Yes" = "catYes"))

# Step 3: Extract estimates

emm_strat<-res_strat %>% 
  unnest(emm) %>% 
  mutate(across(is.numeric, ~round(.,1)),
         "SMR (95 % CI)" = paste0(rate, " (", asymp.LCL, ", ", asymp.UCL, ")")) %>% 
  select(Condition = condition, Category = cat, "SMR (95 % CI)") %>% 
  arrange(Condition, Category) %>% 
  left_join(p, by=c("Condition", "Category")) %>% 
  mutate(p = case_when(p < 0.001~"< 0.001",
                       TRUE~paste("= ",round(p, 2))),
         p = case_when(Category == "No"~p==NA,
                       TRUE~p))

# Step 4: Write to excel for further processing outside R

writexl::write_xlsx(emm_strat, file.path(path_res, "tables/supplemental-table-s4-emm-stratified-0503255.xlsx"))

# Step 5: Make plot

res_strat %>% 
  unnest(emm) %>% 
  select(Condition = condition, Category = cat, rate, asymp.LCL, asymp.UCL) %>% 
  arrange(Condition, Category) %>% 
  left_join(p, by=c("Condition", "Category")) %>% 
  mutate(p = case_when(p < 0.001~"p < 0.001",
                       TRUE~paste("p = ", round(p, 2))),
         p = case_when(Category == "No"~p==NA,
                       TRUE~p),
         Condition = as.factor(Condition),
         Condition = fct_relevel(Condition, "prev_cvd", "prev_dia", "prev_obesity", "prev_lipid", "pre_tsb", "illegale", "polydrug", "benzo_lastyear", "z_lastyear", "opioids_lastyear"),
         Condition = fct_recode(Condition, "Illegal substance use" = "illegale",
                                "Polysubstance use" = "polydrug",
                                "Previous addiction treatment" = "pre_tsb",
                                "Previous CVD" = "prev_cvd",
                                "Previous diabetes (any)" = "prev_dia",
                                "Previous overweight/obesity" = "prev_obesity",
                                "Previous dyslipidemia" = "prev_lipid",
                                "Benzodiazepine prescription" = "benzo_lastyear",
                                "Z-drug prescription" = "z_lastyear",
                                "Opioid prescription" = "opioids_lastyear")) %>% 
  filter(Condition %in% c("Illegal substance use", "Polysubstance use", "Previous addiction treatment", "Benzodiazepine prescription", "Z-drug prescription", "Opioid prescription")) %>% 
  ggplot(aes(x=Category, y=rate, ymin=asymp.LCL, ymax=asymp.UCL)) +
  geom_pointrange(shape=21, fill="#367c3a", size=0.6) +
  coord_flip() +
  facet_wrap(~Condition, ncol=1) +
  theme_minimal() +
  theme(strip.text = element_text(size=12, face="bold", hjust=0),
        axis.text = element_text(size=12, color="black"),
        axis.title=element_text(size=12, color="black")) +
  xlab("") +
  ylab("asSMR") +
  geom_text(aes(label=p, y = 90, x=1.5))

ggsave(file.path(path_res, "figures/fig-3-stratified-all-070425.png"), dpi=300, width=6, height=6)
  
  
```
